config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from core.user import urls as user_urls
from core.customadmin import urls as customadmin_urls

admin.site.site_title = "Quickly"
admin.site.site_header = "Quickly"
admin.site.index_title = "Site administration"

urlpatterns = [
    path("", include(customadmin_urls)),
    path("admin/", admin.site.urls),
    # path("user/", include(user_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/user/models/users.py
import uuid

from config.models import ActivityTracking
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin,
)
from django.db import models
from django.utils.translation import gettext as _
from django.urls import reverse

# Create your models here.


class AccountManager(BaseUserManager):
    def create_user(self, email, password=None, **kwargs):
        if not email:
            raise ValueError("Users must have a valid email address.")

        if not kwargs.get("username"):
            raise ValueError("Users must have a valid username.")

        account = self.model(
            email=self.normalize_email(email), username=kwargs.get("username")
        )

        account.set_password(password)
        account.save()

        return account

    def create_superuser(self, email, password, **kwargs):
        account = self.create_user(email, password, **kwargs)

        account.is_superuser = True
        account.is_staff = True
        account.save()

        return account


class User(AbstractBaseUser, ActivityTracking, PermissionsMixin):

    ADMIN = "Admin"
    MANAGER = "Manager"

    ROLE_CHOICES = (
        (ADMIN, "Admin"),
        (MANAGER, "Manager"),
    )

    email = models.EmailField(
        null=True, blank=True, unique=True, verbose_name=_("Email")
    )
    username = models.CharField(
        max_length=40,
        blank=True,
        null=True,
        default="",
        unique=True,
        verbose_name=_("Username"),
    )
    first_name = models.CharField(
        max_length=40, blank=True, verbose_name=_("Firstname")
    )
    last_name = models.CharField(max_length=40, blank=True, verbose_name=_("Lastname"))
    role = models.CharField(
        choices=ROLE_CHOICES, max_length=40, blank=True, verbose_name=_("Role")
    )
    profile_image = models.ImageField(
        upload_to="profile_image",
        default="sample.jpg",
        null=True,
        blank=True,
        verbose_name=_("Profile Image"),
    )
    description = models.CharField(
        max_length=255, blank=True, verbose_name=_("Description")
    )

    birth_date = models.CharField(
        max_length=10, default="", blank=True, verbose_name=_("Birthdate")
    )
    address = models.CharField(
        max_length=255, default="", blank=True, verbose_name=_("Address")
    )
    phone = models.CharField(
        max_length=20, default="", blank=True, verbose_name=_("Phone")
    )
    city = models.CharField(max_length=50, blank=True, verbose_name=_("City"))
    state = models.CharField(max_length=50, blank=True, verbose_name=_("State"))
    country = models.CharField(max_length=30, blank=True, verbose_name=_("Country"))
    pincode = models.CharField(max_length=8, blank=True, verbose_name=_("Pincode"))

    unique_id = models.UUIDField(
        default=uuid.uuid4,
        editable=False,
        unique=True,
        verbose_name=_("Unique Id"),
    )

    is_active = models.BooleanField(default=True, verbose_name=_("Is Active"))
    is_staff = models.BooleanField(default=True, verbose_name=_("Is Staff"))

    objects = AccountManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    def __str__(self):
        return self.username

    def get_full_name(self):
        return " ".join([self.first_name, self.last_name])

    def get_short_name(self):
        return self.first_name

    def get_absolute_url(self):
        return reverse("customadmin:index")

    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"
        ordering = ["-created_at"]

core/customadmin/views/generic.py
from braces.views import MultiplePermissionsRequiredMixin
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect
from django.urls import reverse
from django.urls.exceptions import NoReverseMatch
from django.utils.translation import gettext as _
from django.utils.translation import ngettext
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    TemplateView,
    UpdateView,
    View,
)
from django.views.generic.edit import FormView
from django.views.generic.dates import TodayArchiveView
from django.views.generic.dates import DayArchiveView
from extra_views import CreateWithInlinesView, NamedFormsetsMixin, UpdateWithInlinesView
from multi_form_view import MultiFormView, MultiModelFormView

from ..mixins import HasPermissionsMixin, ModelOptsMixin, SuccessMessageMixin
from ..utils import admin_urlname, get_deleted_objects

MSG_CREATED = '"{}" created successfully.'
MSG_UPDATED = '"{}" updated successfully.'
MSG_DELETED = '"{}" deleted successfully.'
MSG_CANCELED = '"{}" canceled successfully.'

# -----------------------------------------------------------------------------
# Generic Views
# -----------------------------------------------------------------------------


class MyView(LoginRequiredMixin, PermissionRequiredMixin, View):
    """View with LoginRequiredMixin and PermissionRequiredMixin."""

    pass


class MyLoginRequiredView(LoginRequiredMixin, View):
    """View with LoginRequiredMixin."""

    pass


class MyTemplateView(LoginRequiredMixin, PermissionRequiredMixin, TemplateView):
    """TemplateView CBV with LoginRequiredMixin and PermissionRequiredMixin."""

    pass


class MyFormView(LoginRequiredMixin, PermissionRequiredMixin, FormView):
    """FormView CBV with LoginRequiredMixin and PermissionRequiredMixin."""

    pass


class MyListView(
    LoginRequiredMixin,
    ModelOptsMixin,
    HasPermissionsMixin,
    ListView,
):
    """ListView CBV with LoginRequiredMixin and PermissionRequiredMixin."""

    pass


class MyDetailView(LoginRequiredMixin, ModelOptsMixin, DetailView):
    """DetailView CBV with LoginRequiredMixin and PermissionRequiredMixin."""

    pass


class MyCreateView(
    LoginRequiredMixin,
    SuccessMessageMixin,
    ModelOptsMixin,
    HasPermissionsMixin,
    CreateView,
):
    """CreateView CBV with LoginRequiredMixin, PermissionRequiredMixin
    and SuccessMessageMixin."""

    def get_success_message(self):
        return MSG_CREATED.format(self.object)

    def get_success_url(self):
        # print("MyCreateView::get_success_url")
        opts = self.model._meta
        return reverse(admin_urlname(opts, "list"))


class MyUpdateView(
    LoginRequiredMixin,
    SuccessMessageMixin,
    ModelOptsMixin,
    HasPermissionsMixin,
    UpdateView,
):
    """UpdateView CBV with LoginRequiredMixin, PermissionRequiredMixin
    and SuccessMessageMixin."""

    def get_permission_required(self):
        """Default to view and change perms."""
        # perms = super().get_permission_required()
        opts = self.model._meta
        codename_view = get_permission_codename("view", opts)
        codename_change = get_permission_codename("change", opts)
        view_perm = f"{opts.app_label}.{codename_view}"
        change_perm = f"{opts.app_label}.{codename_change}"
        perms = (view_perm, change_perm)
        # print(perms)
        return perms

    def get_success_message(self):
        return MSG_UPDATED.format(self.object)

    def get_success_url(self):
        # print("MyUpdateView::get_success_url")
        opts = self.model._meta
        return reverse(admin_urlname(opts, "list"))
        # try:
        #     return reverse(admin_urlname(opts, "list"))
        # except NoReverseMatch:
        #     return reverse(
        #         admin_urlname(opts, "update"), kwargs={"pk": self.get_object().pk}
        #     )


class MyDeleteView(
    LoginRequiredMixin,
    SuccessMessageMixin,
    ModelOptsMixin,
    HasPermissionsMixin,
    DeleteView,
):
    """CBV to delete a model record - both Ajax and POST requests."""

    def get_success_message(self):
        return MSG_DELETED.format(self.object)

    def get_success_url(self):
        # print("MyDeleteView:: get_success_url")
        opts = self.model._meta
        return reverse(admin_urlname(opts, "list"))

    def delete(self, request, *args, **kwargs):
        """Override delete method."""
        response = super().delete(request, *args, **kwargs)
        messages.success(self.request, self.get_success_message())
        if self.request.is_ajax():
            response_data = {}
            response_data["result"] = True
            response_data["message"] = self.get_success_message()
            return JsonResponse(response_data)
        return response

    def get_context_data(self, **kwargs):
        """Get deletable objects."""
        # TODO: Move to deleted objects mixin and reference self?
        ctx = super().get_context_data(**kwargs)
        # print(ctx["opts"].__dict__.keys())

        # Do some extra work here
        opts = self.model._meta

        # Populate deleted_objects, a data structure of all related objects that
        # will also be deleted.
        # deleted_objects, model_count, perms_needed, protected = self.get_deleted_objects([obj], request)
        deleted_objects, model_count, protected = get_deleted_objects([self.object])

        object_name = str(opts.verbose_name)

        # if perms_needed or protected:
        if protected:
            title = _("Cannot delete %(name)s") % {"name": object_name}
        else:
            title = _("Are you sure?")

        ctx["title"] = title
        ctx["deleted_objects"] = deleted_objects
        ctx["model_count"] = dict(model_count).items()
        ctx["protected"] = protected
        return ctx


class MyCancelView(
    LoginRequiredMixin,
    PermissionRequiredMixin,
    SuccessMessageMixin,
    ModelOptsMixin,
    HasPermissionsMixin,
    DetailView,
):
    """CBV with LoginRequiredMixin, PermissionRequiredMixin
    and SuccessMessageMixin."""

    def get_success_message(self):
        return MSG_CANCELED.format(self.object)

    def get_success_url(self):
        opts = self.model._meta
        return reverse(admin_urlname(opts, "list"))

    def cancel(self, request, *args, **kwargs):
        """Call `cancel` method on object."""
        self.object = self.get_object()
        success_url = self.get_success_url()
        if "force" in kwargs:
            self.object.cancel(force=True)
        else:
            self.object.cancel()
        # TODO: self.request or request?
        if self.request.is_ajax():
            response_data = {}
            response_data["result"] = True
            response_data["message"] = self.get_success_message()
            return JsonResponse(response_data)
        messages.success(self.request, self.get_success_message())
        return HttpResponseRedirect(success_url)

    def post(self, request, *args, **kwargs):
        return self.cancel(request, *args, **kwargs)


# -----------------------------------------------------------------------------
# Formset Views
# -----------------------------------------------------------------------------


class MyNewFormsetCreateView(
    LoginRequiredMixin,
    PermissionRequiredMixin,
    NamedFormsetsMixin,
    CreateWithInlinesView,
):
    """CreateView CBV with CreateWithInlinesView."""

    def get_success_url(self):
        # TODO: Should be moved to form_valid
        messages.success(self.request, MSG_CREATED.format(self.object))
        opts = self.model._meta
        return reverse(admin_urlname(opts, "list"))


class MyNewFormsetUpdateView(
    LoginRequiredMixin,
    PermissionRequiredMixin,
    NamedFormsetsMixin,
    UpdateWithInlinesView,
):
    """UpdateView CBV with UpdateWithInlinesView."""

    def get_success_url(self):
        # TODO: Should be moved to form_valid
        messages.success(self.request, MSG_UPDATED.format(self.object))
        opts = self.model._meta
        return reverse(admin_urlname(opts, "list"))


# -----------------------------------------------------------------------------
# Multi Form Views
# -----------------------------------------------------------------------------


class MyMultiModelFormView(
    LoginRequiredMixin,
    PermissionRequiredMixin,
    SuccessMessageMixin,
    ModelOptsMixin,
    HasPermissionsMixin,
    MultiModelFormView,
):

    model = None
    # Object should be set within `forms_valid`
    object = None
    pk_url_kwarg = "pk"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        # Inject the primary object we may be editing
        ctx["object"] = self.object
        return ctx

    def get_success_url(self):
        # print("MyMultiModelFormView::get_success_url")
        # return self.object.get_absolute_url()
        opts = self.model._meta
        return reverse(admin_urlname(opts, "list"))


# -----------------------------------------------------------------------------
# Date Views
# -----------------------------------------------------------------------------


class MyDayArchiveView(
    LoginRequiredMixin,
    PermissionRequiredMixin,
    ModelOptsMixin,
    HasPermissionsMixin,
    DayArchiveView,
):
    """DayArchiveView CBV with LoginRequiredMixin and PermissionRequiredMixin."""

    pass


class MyTodayArchiveView(
    LoginRequiredMixin,
    PermissionRequiredMixin,
    ModelOptsMixin,
    HasPermissionsMixin,
    TodayArchiveView,
):
    """TodayArchiveView CBV with LoginRequiredMixin and PermissionRequiredMixin."""

    pass

core/customadmin/views/groups.py
# -*- coding: utf-8 -*-
from django.db.models.query_utils import Q
from django.template.loader import get_template
from django_datatables_too.mixins import DataTableMixin
from core.customadmin.mixins import HasPermissionsMixin
from core.customadmin.views.generic import (
    MyCreateView,
    MyDeleteView,
    MyListView,
    MyLoginRequiredView,
    MyUpdateView,
)
from django.contrib.auth.models import Group

from ..forms import MyGroupForm

# -----------------------------------------------------------------------------
# Groups
# -----------------------------------------------------------------------------


class GroupListView(MyListView):
    # paginate_by = 25
    model = Group
    queryset = model.objects.none()
    template_name = "customadmin/adminuser/group_list.html"
    permission_required = ("auth.view_group",)


class GroupCreateView(MyCreateView):
    model = Group
    form_class = MyGroupForm
    template_name = "customadmin/adminuser/group_form.html"
    permission_required = ("auth.add_group",)


class GroupUpdateView(MyUpdateView):
    model = Group
    form_class = MyGroupForm
    template_name = "customadmin/adminuser/group_form.html"
    permission_required = ("auth.change_group",)


class GroupDeleteView(MyDeleteView):
    model = Group
    template_name = "customadmin/confirm_delete.html"
    permission_required = ("auth.delete_group",)


class GroupAjaxPagination(DataTableMixin, HasPermissionsMixin, MyLoginRequiredView):
    """Built this before realizing there is
    https://bitbucket.org/pigletto/django-datatables-view."""

    model = Group
    queryset = Group.objects.all()

    def _get_actions(self, obj, **kwargs):
        """Get actions column markup."""
        t = get_template("customadmin/partials/list_basic_actions.html")
        can_update = (
            True
            if "auth.change_group" in self.request.user.get_group_permissions()
            else False
        )
        can_delete = (
            True
            if "auth.delete_group" in self.request.user.get_group_permissions()
            else False
        )
        return t.render(
            {
                "obj": obj,
                "opts": self.model._meta,
                "can_update": can_update,
                "can_delete": can_delete,
            }
        )

    def filter_queryset(self, qs):
        """Return the list of items for this view."""
        # If a search term, filter the query
        if self.search:
            return qs.filter(Q(name__icontains=self.search))
        return qs

    def prepare_results(self, qs):
        # Create row data for datatables
        data = []
        for o in qs:
            data.append(
                {
                    "name": o.name,
                    "actions": self._get_actions(o),
                }
            )
        return data

core/customadmin/views/mixins.py
from django.http import JsonResponse


class AjaxableResponseMixin:
    """
    Mixin to add AJAX support to a form.
    Must be used with an object-based FormView (e.g. CreateView)
    """

    def form_invalid(self, form):
        response = super().form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        else:
            return response

    def form_valid(self, form):
        # We make sure to call the parent's form_valid() method because
        # it might do some processing (in the case of CreateView, it will
        # call form.save() for example).
        response = super().form_valid(form)
        if self.request.is_ajax():
            data = {"pk": self.object.pk}
            return JsonResponse(data)
        else:
            return response

core/customadmin/templates/customadmin/plans/plan_form.html
{% extends 'customadmin/change_form.html' %}
{% load static %}
{% load widget_tweaks %}
{% load admin_extras %}
{% load misc_filters %}
{% load crispy_forms_tags %}
{% load i18n %}


{% block page_content %}
    <form id="{{ opts.model_name }}-form" action="" method="post" enctype="multipart/form-data" autocomplete="off">

        {% include "customadmin/partials/form_hidden_fields.html" %}

        <div class="ibox float-e-margins">

            {% include "customadmin/partials/ibox_title.html" with ibox_title="Info" icon_class="fas fa-user" only %}

            <div class="ibox-content">
                <div class="row">
                    <div class="col-sm-6">
                        {{ form.name|as_crispy_field }}
                    </div>
                    <div class="col-sm-6">
                        {{ form.price|as_crispy_field }}
                    </div>


                    <div class="col-sm-6">
                        {{ form.days|as_crispy_field }}
                    </div>
                    <div class="col-sm-6">
                        {{ form.months|as_crispy_field }}
                    </div>
                    <div class="col-sm-12">
                        {{ form.description|as_crispy_field }}
                    </div>
                    <div class="col-sm-12 mt-2">
                        {% input_icheck form.is_active %}
                    </div>
                </div>
            </div>
            <!-- /ibox-content -->

        </div>
        <!-- /ibox -->

        {% include "customadmin/partials/form_footer.html" %}

    </form>

{% endblock %}


{% block js %}
{{ block.super }}
<script src="{% static 'customadmin/js/userroles.js' %}"></script>

<script>
    $(function() {
        userroles.plans.details();
    });
</script>
{% endblock %}

core/customadmin/templates/customadmin/plans/plan_list.html
{% extends 'customadmin/change_list.html' %}
{% load static %}
{% load admin_extras %}
{% load misc_filters %}
{% load i18n %}


{% block page_content %}
    {% csrf_token %}

    {% include "customadmin/includes/list_header_card.html" with title="Create a new plan" subtitle="Create a new plan." show_button=True %}

    <div class="ibox float-e-margins">
        {% comment %} <div class="ibox-title">
            <div class="ibox-tools">
                {% if perms.users.add_user %}
                <a href="{% url opts|admin_urlname:'create' %}" class="btn btn-primary btn-lg"><i class="fa fa-plus"></i> Add {{ opts.verbose_name|capfirst }}</a>
                {% endif %}
            </div>
        </div> {% endcomment %}

        <div class="ibox-content">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover" id="{{ opts.model_name }}-table">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Price</th>
                            <th>Days</th>
                            <th>Months</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Name</th>
                            <th>Price</th>
                            <th>Days</th>
                            <th>Months</th>
                            <th></th>
                        </tr>
                    </tfoot>
                    <tbody>
                        {% for o in object_list %}
                        <tr>
                            <td>{{ o.name }}</td>
                            <td>{{ o.price }}</td>
                            <td>{{ o.days }}</td>
                            <td>{{ o.months }}</td>
                            </td>
                            <td class="row-actions">
                                {% include "customadmin/partials/list_row_actions.html" %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>

                </table>
            </div>
        </div>
    </div>

{% endblock %}


{% block js %}
{{ block.super }}
<script src="{% static 'customadmin/js/userroles.js' %}"></script>

<script>
    var pagination_url = "{% url opts|admin_urlname:'list-ajax' %}";
    $(function () {
        userroles.plans.index();
    });
</script>
{% endblock %}